language: php

php:
  - 7.0
  - nightly

branches:
  except:
    - development

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --dev -o

script:
  - ./vendor/bin/phpunit --coverage-clover tmp/clover.xml

after_success:
  - ./vendor/bin/test-reporter --coverage-report tmp/clover.xml