language: php

php:
  - 7.0
  - nightly
  - hhvm

branches:
  except:
    - development

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --dev -o

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

success:
  - ./vendor/bin/test-reporter